### ISSUE TITLE
Checklist before release

### ISSUE THREAD

**Issue by ssurbhi560** [ssurbhi560/buying-frenzy#1]
- [x] Data loading script.
- [x] Add `purchase` mutation.
- [x] Add CI (GitHub Action).
- [x] Tests for everything.
- [x] Add test coverage reporting using coveralls.io or codecov.
- [x] Dockerize the app.
  - [x] Migrate before `ENTRYPOINT`.
  - [x] Specify `SECRET_KEY`.
- [x] Add query for filtering based on number of dishes.
- [x] Deployment.
  - [x] Deploy the app.
  - [x] Host it on frenzy.tk?
  - [x] Deploy ElasticSearch.
- [x] Document API.
- [x] Index Restaurant names using Elasticsearch for better relevance.
